# Generated by Django 3.0.4 on 2020-05-03 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=15)),
                ('content', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('challenge_type', models.CharField(choices=[('programming', 'Programming Challenge'), ('gaming', 'Gaming Challenge'), ('sports', 'Sports Challenge'), ('eating', 'Eating Challenge'), ('music', 'Music Challenge'), ('makeup', 'MakeUp Challenge')], max_length=11)),
                ('video', models.CharField(blank=True, max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('challenge_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
