# Generated by Django 3.0.4 on 2020-05-05 13:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desafios', '0002_challenge_like_comment_comment_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Challenge_Like',
            new_name='ChallengeLike',
        ),
        migrations.RenameModel(
            old_name='Comment_Like',
            new_name='CommentLike',
        ),
    ]
