# Generated by Django 3.0.4 on 2020-05-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0006_auto_20200505_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
