# Generated by Django 3.0.4 on 2020-05-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0007_auto_20200505_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
