# Generated by Django 3.0.4 on 2020-05-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0011_auto_20200506_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='video',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
