# Generated by Django 3.0.4 on 2020-05-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0012_auto_20200506_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='desafios.Challenge'),
        ),
    ]
