# Generated by Django 3.0.4 on 2020-05-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0015_auto_20200509_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
