# Generated by Django 3.0.4 on 2020-05-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0017_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(choices=[('programming', 'Programming Challenge'), ('gaming', 'Gaming Challenge'), ('sports', 'Sports Challenge'), ('Culinary', 'Culinary Challenge'), ('music', 'Music Challenge'), ('makeup', 'MakeUp Challenge')], max_length=11),
        ),
    ]
